language: node_js
node_js:
  - '6.6'
before_install:
  - rvm use "$(cat api/.ruby-version)" --install --binary --fuzzy
install:
  - ./scripts/setup.sh
script:
  - ./scripts/test.sh
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
addons:
  ssh_known_hosts: git.heroku.com
