# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 783c9923a73e4638e1c2cade524be296fbf9367f070052b1a86136127b4c10209e764e78a6c6b1f0ed4a01b48a9ad10b6cd8b8633e44ace3e6f597d048e8cb21

test:
  secret_key_base: 62b44a21ecb337c3859d074c20db1ce74ab26779e728dd5be2c9d1036e77ab84563dca4578f6a934dac909977f70b18a294aa7dbb8145423908cc50e247c78dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
