AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb

Rails:
  Enabled: true

# Disables "Use nested module/class definitions instead of compact style" warning
ClassAndModuleChildren:
  Enabled: false

# Disables "Missing top-level class documentation comment" warning
Documentation:
  Enabled: false

# Increases "Line is too long" warning from 80 to 180
Metrics/LineLength:
  Max: 120

# Disables "Missing frozen string literal comment" warning
FrozenStringLiteralComment:
  Enabled: false

# Enforce trailing commas - but only for multilines
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
