source 'https://rubygems.org'

gem 'active_model_serializers', '~> 0.10.0'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'bcrypt', '~> 3.1.7'
gem 'knock'
gem 'rack-cors'
gem 'search_object'

gem 'newrelic_rpm'
gem 'sentry-raven'

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'rubocop', require: false
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end
